---
title: "worksheet_6_lists_+_apply"
output: html_document
date: "2023-02-15"
---

```{r}
# load in data 

survey = readRDS(url("https://github.com/Adv-R-Programming/Adv-R-Reader/raw/main/class_survey.rds"))

```

```{r}
comma_split = function(vector_to_split, possible_columns){
  
  # make a base dataframe with rows for each of our cases.
  output = data.frame(
    'id' = 1:length(vector_to_split)
    )
  
  # iterate through all options and create a column with NAs for it
  for(option in possible_columns){
    
    # make a new column with a character version of each possible option.
    output[, as.character(option)] = NA
    
  }
  
  # fill output df
  for(option in possible_columns){
    
    # fill dataframe iterativly.
    output[ , option] = grepl(option, vector_to_split, ignore.case = TRUE)
    
  }
  
  # clear all know options
  for(option in possible_columns){
    
    # remove all known options
    vector_to_split = gsub(pattern = option, vector_to_split, replacement = '', ignore.case = TRUE)
    
  }
  
  # clear commas and whitespace
  vector_to_split = gsub(pattern = ',', vector_to_split, replacement = '', ignore.case = TRUE)
  vector_to_split = trimws(vector_to_split)
  
  # Fill in 'other'
  output$other = vector_to_split
  # Turn blanks into NAs
  output[output$other == "" & !is.na(output$other), 'other'] = NA
  
  # return output
  return(output)
}
```

# Question 1 

```{r}
# apply lapply to survey df 
lapply(survey[ ,c("coffee_days", "tea_days", "soda/pop_days", "juice_days", "none_days")], FUN = comma_split, possible_columns = c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"))
```

```{r}
# download file into project directory
download.file("https://github.com/Adv-R-Programming/Adv-R-Reader/raw/main/content/class_worksheets/09_apply_lists/09_data.zip", "./09_data.zip")

# unzip into folder
unzip("./09_data.zip", exdir = "./09_data_dir/")
```

```{r}
# vector including all files dealing with econ
econ_data_paths = list.files("./09_data_dir/", pattern = "econ_", full.names = TRUE)
```

```{r}
# read in all econ files 
all_econ_data = lapply(econ_data_paths, read.csv)
```

```{r}
# all_econ_data in a wide format 
library(tidyr)

all_econ_data_wide = lapply(all_econ_data,
      FUN = pivot_wider,
      id_cols = c("GEOID", "NAME"),
      names_from = "variable",
      values_from = c("estimate", "moe"))
```

```{r}
# match file name vectors to data list elements
for(i in 1:length(all_econ_data_wide)){
  
  # get the file name I want
  file_name = basename(econ_data_paths[i])
  
  # add that as a column to the matching list element
  all_econ_data_wide[[i]]$file_name = file_name
}
```

```{r}
# binding the dataframes
merged_econ = do.call(rbind, all_econ_data_wide)
```

# Question 2 